#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Language Wrapper - Complete Translation"""

_CURRENT_LANG = "vi"

VI_TO_EN = {
    " vào ": " to ",
    "- Ổ": "- Drive",
    "1-2 phút": "1-2 minutes",
    "2-3 phút": "2-3 minutes",
    "Bài test sẽ tạo ra một cửa sổ đồ họa nặng trong 60 giây. Hãy quan sát có hiện tượng chớp giật, sọc ngang, hay các đốm màu lạ không? Máy có bị treo hoặc tự khởi động lại không?": "Test will create heavy graphics window for 60 seconds. Observe for flickering, horizontal lines, or strange color spots. Does machine freeze or restart?",
    "Bước này hiển thị thông tin cấu hình mà Windows nhận diện và tự động so sánh với thông tin từ BIOS để phát hiện sai lệch.": "This step displays configuration info that Windows recognizes and auto-compares with BIOS to detect discrepancies.",
    "Bắt đầu Test": "Start Test",
    "Bị dừng bởi người dùng": "Stopped by user",
    "CPU có vấn đề": "CPU has issues",
    "CPU hoạt động tốt": "CPU working well",
    "Camera chưa khởi động - Khung hình 640x480": "Camera not started - Frame 640x480",
    "Camera đã dừng": "Camera stopped",
    "Chú ý đến mục 'Trạng thái'. 'Tốt' là bình thường. 'Lỗi/Cảnh báo' là rủi ro cao. Bước tiếp theo sẽ kiểm tra tốc độ thực tế.": "Pay attention to 'Status'. 'Good' is normal. 'Error/Warning' is high risk. Next step checks actual speed.",
    "Chưa có kết quả test nào": "No test results yet",
    "Chưa kích hoạt": "Not activated",
    "Chỉ hỗ trợ Windows": "Windows only",
    "Chọn từng thành phần\\nđể kiểm tra riêng": "Select individual\\ncomponents to test",
    "Chức năng đang phát triển": "Feature in development",
    "Click phải:": "Right click:",
    "Click phải: 0": "Right click: 0",
    "Click trái:": "Left click:",
    "Click trái: 0": "Left click: 0",
    "Các cài đặt trong BIOS có chính xác và an toàn không?": "Are the BIOS settings correct and safe?",
    "Các thông tin trên được đọc trực tiếp từ BIOS/UEFI và không thể giả mạo từ Windows.\\nHãy so sánh với thông tin quảng cáo của người bán!": "Info above read directly from BIOS/UEFI, cannot be faked from Windows.\\nCompare with seller's advertised specs!",
    "Có, mọi cài đặt đều đúng": "Yes, all settings are correct",
    "Cần cài: pip install pandas openpyxl": "Need: pip install pandas openpyxl",
    "Cần cài: pip install reportlab": "Need: pip install reportlab",
    "Dựa trên phân tích trên, đánh giá tình trạng pin:": "Based on analysis above, battery condition:",
    "ESC để dừng": "ESC to stop",
    "GPU Stress Test - Nhấn ESC để thoát": "GPU Stress Test - Press ESC to exit",
    "GPU có vấn đề": "GPU has issues",
    "GPU hoạt động tốt": "GPU working well",
    "GPU không ổn định": "GPU unstable",
    "GPU là trái tim của đồ họa và game. Một GPU lỗi hoặc quá nhiệt có thể gây ra hiện tượng 'rác' hình (artifacts), treo máy hoặc sụt giảm FPS nghiêm trọng.": "GPU is heart of graphics and gaming. Faulty or overheating GPU can cause artifacts, freezing or severe FPS drops.",
    "GPU ổn định": "GPU stable",
    "Giám sát nhiệt độ và hiệu năng real-time giúp phát hiện vấn đề tản nhiệt, throttling và hiệu năng không ổn định.": "Real-time temperature and performance monitoring helps detect cooling issues, throttling and unstable performance.",
    "Gõ lần lượt tất cả các phím. Phím bạn gõ sẽ sáng lên màu xanh dương, và chuyển sang xanh lá khi được nhả ra. Vẽ trên vùng test touchpad, thử click trái/phải.": "Press all keys sequentially. Keys light up blue when pressed, turn green when released. Draw on touchpad test area, try left/right click.",
    "Gợi ý kiểm tra:": "Check suggestions:",
    "Hoàn thành": "Completed",
    "Hoàn thành kiểm tra!\\n\\nBạn có muốn thoát ứng dụng không?": "Testing completed!\\n\\nDo you want to exit?",
    "Hướng dẫn sử dụng\\nchi tiết từng bước": "Detailed step-by-step\\nuser guide",
    "Hệ thống âm thanh quan trọng cho giải trí và họp trực tuyến. Loa bị rè, micro không hoạt động sẽ ảnh hưởng đến trải nghiệm multimedia.": "Audio system important for entertainment and online meetings. Distorted speakers or broken mic affects multimedia experience.",
    "Không thể kiểm tra": "Cannot check",
    "Không thể đọc S.M.A.R.T": "Cannot read S.M.A.R.T",
    "Không tìm thấy": "Not found",
    "Không tìm thấy CPU": "CPU not found",
    "Không tìm thấy GPU": "GPU not found",
    "Không tìm thấy ổ cứng": "Hard drive not found",
    "Không xác định": "Unknown",
    "Không, có cài đặt sai/bị khóa": "No, incorrect settings/locked",
    "Kiểm Tra BIOS": "BIOS Check",
    "Kiểm Tra Ngoại Hình": "Physical Inspection",
    "Kiểm tra chuyên sâu\\nvới stress test": "In-depth testing\\nwith stress tests",
    "Kiểm tra laptop toàn diện - Chuyên nghiệp": "Comprehensive Laptop Testing - Professional",
    "Kiểm tra nhanh\\ncác chức năng chính": "Quick check\\nof main functions",
    "Kém": "Poor",
    "Kết nối mạng ổn định quan trọng cho công việc và giải trí. Test này kiểm tra tốc độ, độ trễ và chất lượng kết nối WiFi/Ethernet.": "Stable network connection important for work and entertainment. This test checks speed, latency and WiFi/Ethernet quality.",
    "Kết quả": "Result",
    "Kết quả CPU Test:": "CPU Test Result:",
    "Kết quả GPU Test:": "GPU Test Result:",
    "Kết quả: Không thể so sánh (thiếu dữ liệu)": "Result: Cannot compare (missing data)",
    "Lưu báo cáo Excel": "Save Excel report",
    "Lưu báo cáo PDF": "Save PDF report",
    "Lỗi": "Error",
    "Lỗi khi chạy lệnh kiểm tra": "Error running check command",
    "Lỗi/Cảnh báo": "Error/Warning",
    "Model Ổ Cứng": "Hard Drive Model",
    "Màn hình là một trong những linh kiện đắt tiền và dễ hỏng nhất. Lỗi điểm chết, hở sáng, ám màu hay 'ung thư panel' (chớp giật ở cạnh viền) là những vấn đề nghiêm trọng.": "Display is one of most expensive and fragile components. Dead pixels, backlight bleeding, color staining or 'panel cancer' (edge flickering) are serious issues.",
    "Một CPU quá nhiệt sẽ tự giảm hiệu năng (throttling) gây giật lag. Bài test này sẽ đẩy CPU lên 100% tải để kiểm tra khả năng tản nhiệt của máy.": "Overheating CPU will throttle causing lag. This test pushes CPU to 100% load to check cooling capability.",
    "Một máy tính có bản quyền Windows hợp lệ đảm bảo bạn nhận được các bản cập nhật bảo mật quan trọng và tránh các rủi ro pháp lý.": "Valid Windows license ensures security updates and avoids legal risks.",
    "Một phím bị liệt, kẹt, hoặc touchpad bị loạn/mất cử chỉ đa điểm sẽ làm gián đoạn hoàn toàn công việc.": "Dead or stuck key, or malfunctioning touchpad/lost multi-touch will completely disrupt work.",
    "Ngày BIOS": "BIOS Date",
    "Nhấn 'Bắt đầu Test' trong 2-5 phút. Theo dõi biểu đồ nhiệt độ. Nếu nhiệt độ ổn định dưới 95°C và không có hiện tượng treo máy, hệ thống tản nhiệt hoạt động tốt.": "Click 'Start Test' for 2-5 minutes. Monitor temperature chart. If temp stays below 95°C without freezing, cooling works well.",
    "Nhấn 'Bắt đầu Test' để chạy lệnh kiểm tra trạng thái kích hoạt Windows. Kết quả sẽ hiển thị bên dưới.": "Click 'Start Test' to check Windows activation status. Results will display below.",
    "Nhấn 'Bắt đầu Test' để chạy test kết hợp 3-5 phút. Quan sát nhiệt độ và hiệu năng.": "Click 'Start Test' to run combined test for 3-5 minutes. Observe temperature and performance.",
    "Nhấn 'Bắt đầu Test' để chạy test màn hình tự động. Test sẽ hiển thị các màu khác nhau, nhấn ESC để dừng bất cứ lúc nào.": "Click 'Start Test' to run automatic screen test. Test displays different colors, press ESC to stop anytime.",
    "Nhấn 'Bắt đầu Test' để kiểm tra kết nối Internet, DNS, tốc độ mạng và thông tin WiFi.": "Click 'Start Test' to check Internet connection, DNS, network speed and WiFi info.",
    "Nhấn 'Bắt đầu Test' để kiểm tra tốc độ ổ cứng thực tế.": "Click 'Start Test' to check actual hard drive speed.",
    "Nhấn 'Bắt đầu Test' để mở camera. Kiểm tra chất lượng hình ảnh, độ phân giải và che camera để test phát hiện vật cản.": "Click 'Start Test' to open camera. Check image quality, resolution and cover camera to test obstruction detection.",
    "Nhấn 'Bắt đầu Test' để đọc thông tin phần cứng từ BIOS. Sau đó so sánh với thông tin quảng cáo của người bán.": "Click 'Start Test' to read hardware info from BIOS. Then compare with seller's advertised specs.",
    "Nhấn 'Start Monitor' để bắt đầu giám sát. Có thể chạy Stress Test để kiểm tra khả năng tản nhiệt dưới tải cao.": "Click 'Start Monitor' to begin monitoring. Can run Stress Test to check cooling under high load.",
    "Phát bài nhạc test và kiểm tra micro với biểu đồ sóng âm.": "Play test music and check microphone with waveform chart.",
    "Pin là nguồn năng lượng di động của laptop. Pin hỏng hoặc chai sẽ giảm thời gian sử dụng và có thể gây nguy hiểm.": "Battery is laptop's mobile power source. Damaged or degraded battery reduces usage time and may be dangerous.",
    "Pygame không có sẵn. Cài đặt: pip install pygame": "Pygame not available. Install: pip install pygame",
    "Rất tốt": "Excellent",
    "So sánh tự động:": "Auto compare:",
    "Sẵn sàng test": "Ready to test",
    "Test sẽ hiển thị: Đen → Trắng → Đỏ → Xanh Lá → Xanh Dương\\nMỗi màu 3 giây. Nhấn ESC để dừng.": "Test displays: Black → White → Red → Green → Blue\\nEach color 3 seconds. Press ESC to stop.",
    "Test tổng hợp CPU+GPU+RAM để đảm bảo hệ thống ổn định dưới tải nặng kéo dài.": "Combined CPU+GPU+RAM test to ensure system stability under prolonged heavy load.",
    "Test đã được dừng bởi người dùng.": "Test stopped by user.",
    "Thành công": "Success",
    "Thông tin pin sẽ được tự động thu thập. Kiểm tra các thông số dưới đây và đánh giá tình trạng pin.": "Battery info will be automatically collected. Check parameters below and assess battery condition.",
    "Thông tin định danh phần cứng:": "Hardware fingerprint information:",
    "Thời gian:": "Time:",
    "Tiến độ:": "Progress:",
    "Trung bình": "Average",
    "Trạng thái": "Status",
    "Trạng thái:": "Status:",
    "Tìm hiểu về\\nLaptopTester Pro": "Learn about\\nLaptopTester Pro",
    "Tình trạng vật lý tổng thể của máy như thế nào?": "What is overall physical condition?",
    "Tốc độ chậm": "Slow speed",
    "Tốc độ đọc/ghi ảnh hưởng trực tiếp đến hiệu năng hệ thống.": "Read/write speed directly affects system performance.",
    "Tốt": "Good",
    "Webcam cần thiết cho video call và họp trực tuyến. Camera không hoạt động hoặc chất lượng kém sẽ ảnh hưởng đến giao tiếp.": "Webcam necessary for video calls and online meetings. Non-working camera or poor quality affects communication.",
    "Windows chưa được kích hoạt": "Windows not activated",
    "Windows được kích hoạt vĩnh viễn": "Windows permanently activated",
    "Yếu": "Weak",
    "\\n❌ NHỮNG ĐIỀU CẦN TRÁNH:": "\\n❌ THINGS TO AVOID:",
    "\\n💡 Cách khắc phục:": "\\n💡 How to fix:",
    "\\n📋 CÁCH SẠC VÀ SỬ DỤNG PIN ĐÚNG CÁCH:": "\\n📋 PROPER BATTERY CHARGING AND USAGE:",
    "Đang chạy vòng lặp stress...": "Running stress loop...",
    "Đang khởi tạo Pygame...": "Initializing Pygame...",
    "Đang kiểm tra...": "Checking...",
    "Đang tải...": "Loading...",
    "Đang xả cache ghi xuống đĩa...": "Flushing write cache to disk...",
    "Đang đọc...": "Reading...",
    "Đây là bước quan trọng nhất để chống lừa đảo. Các thông tin dưới đây được đọc trực tiếp từ BIOS và linh kiện phần cứng. Chúng cực kỳ khó làm giả từ bên trong Windows.": "Most important step to prevent fraud. Info below read directly from BIOS and hardware. Extremely difficult to fake from Windows.",
    "Đã kích hoạt vĩnh viễn": "Permanently activated",
    "Đã lấy định danh phần cứng": "Hardware fingerprint obtained",
    "Đóng ứng dụng\\nLaptopTester Pro": "Close\\nLaptopTester Pro",
    "Để xác minh kết quả AI và kiểm tra sâu hơn, hãy sử dụng các công cụ chuyên nghiệp sau:": "To verify AI results and check deeper, use these professional tools:",
    "Định danh phần cứng đã hoàn thành. Bạn có muốn tiếp tục?": "Hardware fingerprinting completed. Do you want to continue?",
    "Đối chiếu thông tin dưới đây với bước trước và với thông tin quảng cáo. Nếu mọi thứ khớp, chọn 'Cấu hình khớp'.": "Cross-check info below with previous step and advertised specs. If everything matches, select 'Configuration matches'.",
    "Ổ cứng sắp hỏng là mối rủi ro mất dữ liệu cực lớn. Bước này đọc 'báo cáo y tế' (S.M.A.R.T.) của ổ cứng để đánh giá độ bền.": "Failing hard drive is huge data loss risk. This step reads drive's 'health report' (S.M.A.R.T.) to assess durability.",
    "Ổ cứng:": "Hard drive:",
    "• Cập nhật BIOS và driver": "• Update BIOS and drivers",
    "• Di chuyển chuột/touchpad trên vùng test\\n• Click trái và phải để test\\n• Thử cuộn 2 ngón tay (touchpad)": "• Move mouse/touchpad on test area\\n• Left and right click to test\\n• Try two-finger scroll (touchpad)",
    "• Kiểm tra BIOS: CPU Frequency → Auto/Dynamic": "• Check BIOS: CPU Frequency → Auto/Dynamic",
    "• Kiểm tra adapter nguồn (phải đúng watt)": "• Check power adapter (must be correct wattage)",
    "• Power limit - Nguồn không đủ mạnh": "• Power limit - Insufficient power",
    "• Quá nhiệt (>85°C) - Tản nhiệt kém": "• Overheating (>85°C) - Poor cooling",
    "• Tắt phần mềm quản lý nguồn của hãng": "• Disable manufacturer's power management software",
    "• Vệ sinh quạt tản nhiệt, thay keo tản nhiệt": "• Clean cooling fan, replace thermal paste",
    "• Windows: Chế độ nguồn → Hiệu năng cao": "• Windows: Power mode → High performance",
    "← Quay lại": "← Back",
    "⏹️ Dừng": "⏹️ Stop",
    "⏹️ Đã dừng nhạc": "⏹️ Music stopped",
    "▶️ Chạy Test": "▶️ Run Test",
    "▶️ CƠ BẢN": "▶️ BASIC",
    "⚙️ Checklist Kiểm Tra BIOS Chi Tiết": "⚙️ Detailed BIOS Check Checklist",
    "⚙️ Chế Độ Cơ Bản": "⚙️ Basic Mode",
    "⚠️ Cảnh báo: Có sai lệch - Kiểm tra lại!": "⚠️ Warning: Mismatch detected - Check again!",
    "⚠️ LƯU Ý: Ứng dụng được phát triển dựa trên AI nên có thể có sai sót. Khuyến khích kiểm tra thêm bằng các ứng dụng chuyên dụng được cung cấp bên dưới.": "⚠️ NOTE: App developed with AI may have errors. Recommend additional checks with specialized apps provided below.",
    "⚠️ TÌNH TRẠNG: Pin bắt đầu suy giảm": "⚠️ CONDITION: Battery starting to degrade",
    "⚠️ TÌNH TRẠNG: Pin suy giảm nghiêm trọng": "⚠️ CONDITION: Battery severely degraded",
    "⚡ Hiệu Năng CPU:": "⚡ CPU Performance:",
    "⛔ CẢNH BÁO NGHIÊM TRỌNG - MẬT KHẨU BIOS": "⛔ CRITICAL WARNING - BIOS PASSWORD",
    "✅ Hoàn thành phát file stereo test": "✅ Stereo test file playback completed",
    "✅ Hoàn thành test âm thanh": "✅ Audio test completed",
    "✅ Kết quả: Khớp": "✅ Result: Match",
    "✅ Phát tone test 440Hz": "✅ Playing 440Hz test tone",
    "✅ Test hoàn thành": "✅ Test completed",
    "✅ TÌNH TRẠNG: Pin còn tốt": "✅ CONDITION: Battery still good",
    "✅ Đã dừng ghi âm": "✅ Recording stopped",
    "✅ Đã ghi âm 5 giây": "✅ Recorded 5 seconds",
    "✓ CPU Tốt": "✓ CPU Good",
    "✓ Chấp Nhận": "✓ Accept",
    "✓ Hệ thống ổn định": "✓ System stable",
    "✖ Đóng": "✖ Close",
    "✗ CPU Có Vấn Đề": "✗ CPU Has Issues",
    "✗ Có vấn đề": "✗ Has issues",
    "❌ Không phát hiện pin hoặc đây là máy bàn": "❌ No battery detected or this is desktop",
    "❌ Không tìm thấy camera hoạt động": "❌ No working camera found",
    "❌ OpenCV không có sẵn. Cài đặt: pip install opencv-python": "❌ OpenCV not available. Install: pip install opencv-python",
    "❌ THOÁT": "❌ EXIT",
    "❌ Test âm thanh thất bại": "❌ Test âm thanh thất bại",
    "❌ Thoát": "❌ Exit",
    "🇻🇳 Tiếng Việt": "🇻🇳 Vietnamese",
    "🎤 Ghi âm": "🎤 Record",
    "🎤 Đang ghi âm... Nói vào micro": "🎤 Recording... Speak into microphone",
    "🎯 Chọn chế độ kiểm tra phù hợp:": "🎯 Select appropriate test mode:",
    "🎵 Phát Stereo Test": "🎵 Play Stereo Test",
    "🎵 Phát file stereo_test.mp3...": "🎵 Playing stereo_test.mp3...",
    "🏠 Trang chủ": "🏠 Home",
    "💡 Khuyến khích so sánh kết quả với các tools này để đảm bảo độ chính xác cao nhất.": "💡 Recommend comparing results with these tools to ensure highest accuracy.",
    "💡 Khả Năng Sử Dụng Phần Cứng": "💡 Hardware Capability",
    "💡 LỜI KHUYÊN VỀ SỨC KHỎE PIN": "💡 BATTERY HEALTH ADVICE",
    "💻 Developed by: Laptop Lê Ẩn & Gemini AI": "💻 Developed by: Laptop Lê Ẩn & Gemini AI",
    "💻 Phát triển bởi: Laptop Lê Ẩn & Gemini AI": "💻 Developed by: Laptop Lê Ẩn & Gemini AI",
    "💻 Vỏ Máy & Bản Lề:": "💻 Chassis & Hinges:",
    "📊 Kết Quả CPU Stress Test": "📊 CPU Stress Test Results",
    "📊 Kết Quả GPU Stress Test": "📊 GPU Stress Test Results",
    "📊 Phân Tích Chi Tiết": "📊 Detailed Analysis",
    "📋 Checklist Kiểm Tra Bản Quyền": "📋 License Check Checklist",
    "📋 Checklist Định Danh Phần Cứng": "📋 Hardware Fingerprint Checklist",
    "📋 Chi Tiết Kết Quả Từng Bước": "📋 Step-by-Step Results Details",
    "📍 237/1C Tôn Thất Thuyết, P. Vĩnh Hội, (P.3, Q.4 cũ), TPHCM": "📍 237/1C Ton That Thuyet, Vinh Hoi Ward, (Old Ward 3, Dist 4), HCMC",
    "📖 GIỚI THIỆU": "📖 ABOUT",
    "📖 Giới Thiệu": "📖 About",
    "📚 HƯỚNG DẪN": "📚 GUIDE",
    "📚 Hướng Dẫn": "📚 Guide",
    "🔋 Mức Pin Hiện Tại:": "🔋 Current Battery Level:",
    "🔋 Phân Tích Pin Chi Tiết": "🔋 Detailed Battery Analysis",
    "🔌 Cổng Kết Nối:": "🔌 Ports:",
    "🔍 Checklist Kiểm Tra Ngoại Hình Chi Tiết": "🔍 Detailed Physical Inspection Checklist",
    "🔍 Nguyên nhân có thể:": "🔍 Possible causes:",
    "🔑 Cách Vào BIOS:": "🔑 How to Enter BIOS:",
    "🔒 BẢO MẬT KHÁC:": "🔒 OTHER SECURITY:",
    "🔒 PHÁT HIỆN KHÓA XUNG CPU": "🔒 CPU FREQUENCY LOCK DETECTED",
    "🔥 CHUYÊN GIA": "🔥 EXPERT",
    "🔥 Chế Độ Chuyên Gia": "🔥 Expert Mode",
    "🔧 Chọn Bài Test Riêng Lẻ": "🔧 Select Individual Tests",
    "🔧 Kiểm Tra Riêng Lẻ": "🔧 Individual Testing",
    "🔧 RIÊNG LẺ": "🔧 INDIVIDUAL",
    "🔩 Ốc Vít & Tem Bảo Hành:": "🔩 Screws & Warranty Seals:",
    "🔴 LENOVO THINKPAD - KIỂM TRA ĐẶC BIỆT:": "🔴 LENOVO THINKPAD - SPECIAL CHECK:",
    "🔴 THINKPAD - CÀI ĐẶT KHÁC:": "🔴 THINKPAD - OTHER SETTINGS:",
    "🚨 CẢNH BÁO: Nhiệt độ nguy hiểm! CPU có thể bị hỏng.": "🚨 WARNING: Dangerous temperature! CPU may be damaged.",
    "🤖 Đánh giá của AI": "🤖 AI Assessment",

    "Chọn từng thành phần\nđể kiểm tra riêng": "Select individual\ncomponents to test",
    "Các thông tin trên được đọc trực tiếp từ BIOS/UEFI và không thể giả mạo từ Windows.\nHãy so sánh với thông tin quảng cáo của người bán!": "Info above read directly from BIOS/UEFI, cannot be faked from Windows.\nCompare with seller's advertised specs!",
    "Hoàn thành kiểm tra!\n\nBạn có muốn thoát ứng dụng không?": "Testing completed!\n\nDo you want to exit?",
    "Hướng dẫn sử dụng\nchi tiết từng bước": "Detailed step-by-step\nuser guide",
    "Kiểm tra chuyên sâu\nvới stress test": "In-depth testing\nwith stress tests",
    "Kiểm tra nhanh\ncác chức năng chính": "Quick check\nof main functions",
    "Test sẽ hiển thị: Đen → Trắng → Đỏ → Xanh Lá → Xanh Dương\nMỗi màu 3 giây. Nhấn ESC để dừng.": "Test displays: Black → White → Red → Green → Blue\nEach color 3 seconds. Press ESC to stop.",
    "Tìm hiểu về\nLaptopTester Pro": "Learn about\nLaptopTester Pro",
    "\n❌ NHỮNG ĐIỀU CẦN TRÁNH:": "\n❌ THINGS TO AVOID:",
    "\n💡 Cách khắc phục:": "\n💡 How to fix:",
    "\n📋 CÁCH SẠC VÀ SỬ DỤNG PIN ĐÚNG CÁCH:": "\n📋 PROPER BATTERY CHARGING AND USAGE:",
    "Đóng ứng dụng\nLaptopTester Pro": "Close\nLaptopTester Pro",
    "• Di chuyển chuột/touchpad trên vùng test\n• Click trái và phải để test\n• Thử cuộn 2 ngón tay (touchpad)": "• Move mouse/touchpad on test area\n• Left and right click to test\n• Try two-finger scroll (touchpad)",
    "❌ Test âm thanh thất bại": "❌ Audio test failed",

    "Chi tiết": "Details",
    "Code: VS, Android Studio, Docker\nVM: 3-4 máy ảo\n50+ Chrome tabs": "Code: VS, Android Studio, Docker\nVM: 3-4 virtual machines\n50+ Chrome tabs",
    "Hiển thị nhận định khả năng sử dụng phần cứng": "Display hardware capability assessment",
    "Hàm chung phân tích khả năng phần cứng": "Common function to analyze hardware capability",
    "Học Tập": "Study",
    "Văn Phòng": "Office",
    "Văn Phòng & Code": "Office & Code",
    "Zoom, Teams\nWord, PPT\nTra cứu web": "Zoom, Teams\nWord, PPT\nWeb browsing",
    "Đồ Họa Pro": "Pro Graphics",

    "Cấu hình có khớp với thông tin quảng cáo không?": "Does configuration match advertised specs?",
    "Cấu hình khớp": "Configuration matches",
    "Có sai lệch": "Mismatch detected",
    "Vỏ máy có trầy xước, móp méo, nứt vỡ không?": "Any scratches, dents, or cracks on chassis?",
    "Bản lề mở đóng có mượt, kêu cót két không?": "Hinges smooth, any creaking sounds?",
    "Ốc vít có bị tháo, tem bảo hành còn nguyên không?": "Screws removed? Warranty seals intact?",
    "Bàn phím có phím liệt, kẹt, chữ mờ không?": "Any dead/stuck keys, faded letters?",
    "Touchpad có hoạt động tốt, cử chỉ đa điểm OK không?": "Touchpad working well, multi-touch gestures OK?",
    "Cổng USB, HDMI, audio có hoạt động không?": "USB, HDMI, audio ports working?",
    "Màn hình có điểm chết, hở sáng, ám màu không?": "Any dead pixels, backlight bleeding, color staining?",
    "Loa có rè, méo, mất kênh không?": "Speakers distorted, channel loss?",
    "Camera có hoạt động, hình ảnh rõ không?": "Camera working, image clear?",
    "Pin có phồng, nóng bất thường không?": "Battery swollen, abnormally hot?",
    "Vào BIOS và kiểm tra các thông tin sau:": "Enter BIOS and check following info:",
    "Ngày sản xuất BIOS (BIOS Date)": "BIOS manufacture date",
    "Serial Number (SN) - Không thể giả mạo": "Serial Number (SN) - Cannot be faked",
    "Model chính xác của máy": "Exact machine model",
    "Cấu hình CPU, RAM, Storage": "CPU, RAM, Storage configuration",
    "Secure Boot: Enabled/Disabled": "Secure Boot: Enabled/Disabled",
    "Virtualization: Enabled/Disabled": "Virtualization: Enabled/Disabled",
    "SATA Mode: AHCI/RAID": "SATA Mode: AHCI/RAID",
    "Boot Mode: UEFI/Legacy": "Boot Mode: UEFI/Legacy",
    "Có mật khẩu BIOS không? (Cảnh báo nếu có)": "BIOS password set? (Warning if yes)",
    "Có khóa xung CPU không? (Undervolting/Throttling)": "CPU frequency locked? (Undervolting/Throttling)",
    "Dung lượng thiết kế (Design Capacity)": "Design Capacity",
    "Dung lượng đầy (Full Charge Capacity)": "Full Charge Capacity",
    "Sức khỏe pin (Battery Health)": "Battery Health",
    "Số chu kỳ sạc (Cycle Count)": "Cycle Count",
    "Tình trạng pin": "Battery condition",
    "Pin còn tốt (>80%)": "Battery good (>80%)",
    "Pin bắt đầu suy giảm (60-80%)": "Battery degrading (60-80%)",
    "Pin yếu (<60%)": "Battery weak (<60%)",
    "Cần thay pin": "Need battery replacement",
    "Tổng số bước đã test": "Total steps tested",
    "Số bước đạt": "Steps passed",
    "Số bước cảnh báo": "Steps with warnings",
    "Số bước lỗi": "Steps failed",
    "Số bước bỏ qua": "Steps skipped",
    "Tỷ lệ thành công": "Success rate",
    "Đánh giá tổng thể": "Overall assessment",
    "Máy ở tình trạng tốt": "Machine in good condition",
    "Máy có một số vấn đề nhỏ": "Machine has minor issues",
    "Máy có vấn đề nghiêm trọng": "Machine has serious issues",
    "Không nên mua": "Not recommended to buy",
    "Kiểm tra ngoại hình": "Physical inspection",
    "Kiểm tra BIOS": "BIOS check",
    "Định danh phần cứng": "Hardware fingerprint",
    "Bản quyền Windows": "Windows license",
    "Cấu hình hệ thống": "System configuration",
    "Sức khỏe ổ cứng": "Hard drive health",
    "Kiểm tra màn hình": "Screen test",
    "Bàn phím & Touchpad": "Keyboard & Touchpad",
    "Cổng kết nối": "Ports & Connectivity",
    "Pin laptop": "Battery health",
    "Loa & Micro": "Speakers & Microphone",
    "Mạng & WiFi": "Network & WiFi",
    "CPU Stress Test": "CPU Stress Test",
    "GPU Stress Test": "GPU Stress Test",
    "Tốc độ ổ cứng": "Hard drive speed",
    "Giám sát nhiệt": "Thermal monitoring",

    "Tình trạng vật lý phản ánh cách chủ cũ sử dụng máy. Các vết nứt, móp, bản lề lỏng hay ốc vít bị toét có thể là dấu hiệu máy bị rơi hoặc đã qua sửa chữa không chuyên nghiệp.": "Physical condition reflects how previous owner used machine. Cracks, dents, loose hinges or stripped screws may indicate drops or unprofessional repairs.",
    "Kiểm tra vỏ máy, bản lề, cổng kết nối, ốc vít, tem bảo hành. Đánh giá tổng thể tình trạng vật lý.": "Check chassis, hinges, ports, screws, warranty seals. Assess overall physical condition.",
    "✓ Vỏ máy: Vết nứt, móp méo (đặc biệt góc máy)": "✓ Chassis: Cracks, dents (especially corners)",
    "✓ Bản lề: Mở/đóng 10-15 lần, nghe tiếng kêu kèn kẹt": "✓ Hinges: Open/close 10-15 times, listen for creaking",
    "✓ Bản lề giữ góc: Không rơ, không tự đóng": "✓ Hinge holds angle: No wobble, doesn't self-close",
    "✓ Vết nứt gần bản lề: DẤU HIỆU NGUY HIỂM": "✓ Cracks near hinges: DANGER SIGN",
    "✓ Cổng sạc: Cắm và lay nhẹ, KHÔNG được lỏng": "✓ Charging port: Plug and wiggle gently, must NOT be loose",
    "✓ USB: Cắm thử USB, kiểm tra độ chặt": "✓ USB: Test plug, check tightness",
    "✓ HDMI/DisplayPort: Không bị lỏng lẻo": "✓ HDMI/DisplayPort: Not loose",
    "✓ Audio jack: Cắm tai nghe thử": "✓ Audio jack: Test with headphones",
    "✓ Ốc vít: Không toét đầu (dấu hiệu tháo lắp)": "✓ Screws: Not stripped (sign of disassembly)",
    "✓ Tem bảo hành: Còn nguyên, không bị bóc": "✓ Warranty seals: Intact, not peeled",
    "✓ Serial number: Khớp với BIOS và sticker": "✓ Serial number: Matches BIOS and sticker",
    "✓ Khe tản nhiệt: Không bị bịt tắc bụi": "✓ Cooling vents: Not blocked by dust",
    "✓ Tem Lenovo chính hãng: Hologram, không nhòe": "✓ Genuine Lenovo sticker: Hologram, not blurry",
    "✓ Sticker dưới đáy: COA Windows, Serial, Model": "✓ Bottom stickers: COA Windows, Serial, Model",
    "✓ Asset tag: ThinkPad doanh nghiệp thường có": "✓ Asset tag: Corporate ThinkPads usually have",
    "✓ TrackPoint (nút đỏ): Hoạt động, không bị lỏng": "✓ TrackPoint (red dot): Working, not loose",
    "✓ ThinkLight/Đèn bàn phím: Test hoạt động": "✓ ThinkLight/Keyboard backlight: Test working",
    "✓ Khe Kensington Lock: Không bị gãy": "✓ Kensington Lock slot: Not broken",
    "⚠️ Kiểm tra BIOS có bị khóa Computrace không!": "⚠️ Check if BIOS has Computrace lock!",
    "Ổ cứng": "Hard Drive",
    "Dung lượng": "Capacity",
    "Loại": "Type",
    "Nhiệt độ": "Temperature",
    "Nhấn 'Bắt đầu Test' để chạy test màn hình tự động. Test sẽ hiển thị các màu khác nhau, nhấn ESC để dừng bất cứ lúc nào.": "Click 'Start Test' to run automatic screen test. Test displays different colors, press ESC to stop anytime.",
    "Gõ lần lượt tất cả các phím. Phím bạn gõ sẽ sáng lên màu xanh dương, và chuyển sang xanh lá khi được nhả ra. Vẽ trên vùng test touchpad, thử click trái/phải.": "Press all keys sequentially. Keys light up blue when pressed, turn green when released. Draw on touchpad test area, try left/right click.",
    "Phát bài nhạc test và kiểm tra micro với biểu đồ sóng âm.": "Play test music and check microphone with waveform chart.",
    "Bước": "Step",
    "Kết quả": "Result",
    "Đạt": "Passed",
    "Cảnh báo": "Warning",
    "Bỏ qua": "Skipped",

    "Văn Phòng": "Office",
    "Office: Word, Excel\nWeb: Facebook, YouTube\nPhim: Netflix 1080p": "Office: Word, Excel\nWeb: Facebook, YouTube\nMovies: Netflix 1080p",
    "Học Tập": "Study",
    "Đồ Họa Pro": "Pro Graphics",
    "3D: AutoCAD, SolidWorks\nRender: Blender, V-Ray\nAI: TensorFlow, PyTorch": "3D: AutoCAD, SolidWorks\nRender: Blender, V-Ray\nAI: TensorFlow, PyTorch",
    "Gaming 1080p": "Gaming 1080p",
    "Game: Esports titles\nCasual AAA games\nLight 3D work": "Game: Esports titles\nCasual AAA games\nLight 3D work",

    "Sạc điện": "Charging",
    "Dùng pin": "On battery",
    "Thời gian sạc đầy": "Time to full charge",
    "Thời gian còn lại": "Time remaining",
    "Đang sạc điện": "Charging",
    "Dung lượng thiết kế:": "Design capacity:",
    "Dung lượng hiện tại:": "Current capacity:",
    "Sức khỏe pin:": "Battery health:",
    "Chu kỳ sạc:": "Charge cycles:",
    "chu kỳ": "cycles",
    "Công nghệ:": "Technology:",
    "Lithium-ion": "Lithium-ion",
    "Sạc đúng cách:": "Proper charging:",
    "Giữ pin 20-80% để kéo dài tuổi thọ": "Keep battery 20-80% to extend lifespan",
    "Không để pin xuống 0% thường xuyên": "Don't let battery reach 0% frequently",
    "Sạc qua đêm không sao (có bảo vệ quá sạc)": "Overnight charging is OK (has overcharge protection)",
    "Rút sạc khi đầy nếu có thể": "Unplug when full if possible",
    "Tránh:": "Avoid:",
    "Nhiệt độ quá cao (>35°C) hoặc quá thấp (<0°C)": "Extreme temperatures (>35°C or <0°C)",
    "Để máy nóng khi sạc": "Keeping laptop hot while charging",
    "Sạc bằng sạc kém chất lượng": "Using low-quality chargers",
    "Để pin hết hoàn toàn lâu ngày": "Leaving battery completely drained for long periods",
    "Cách khắc phục pin yếu:": "How to fix weak battery:",
    "Hiệu chỉnh pin: Sạc đầy 100%, dùng hết 0%, sạc lại 100%": "Calibrate battery: Charge to 100%, drain to 0%, charge to 100%",
    "Kiểm tra ứng dụng ngốn pin trong Task Manager": "Check battery-draining apps in Task Manager",
    "Cập nhật BIOS và driver": "Update BIOS and drivers",
    "Nếu <60%: Cân nhắc thay pin mới": "If <60%: Consider battery replacement",

    "BIOS chứa các cài đặt nền tảng. Kiểm tra để đảm bảo hiệu năng tối ưu và không bị khóa bởi các tính năng doanh nghiệp.": "BIOS contains foundation settings. Check to ensure optimal performance and not locked by enterprise features.",
    "Xem checklist bên dưới để kiểm tra từng mục trong BIOS": "See checklist below to check each item in BIOS",
    "Bảo mật & Định danh": "Security & Identity",
    "Cài đặt chính xác": "Settings correct",
    "Có vấn đề với BIOS": "BIOS issues",
    "BÁO CÁO KIỂM TRA LAPTOP": "LAPTOP TEST REPORT",
    "Bình thường": "Normal",
    "CPU không ổn định": "CPU unstable",
    "CPU ổn định": "CPU stable",
    "Có lỗi": "Has errors",
    "Có một số vấn đề nhỏ, cần kiểm tra kỹ trước khi quyết định.": "Has minor issues, need careful check before decision.",
    "Có vấn đề": "Has issues",
    "Có ổ cứng lỗi": "Hard drive error",
    "Hoạt động tốt": "Working well",
    "Không có vấn đề": "No issues",
    "Không hoạt động": "Not working",
    "Không rõ": "Unknown",
    "Không ổn định": "Unstable",
    "Ổn định": "Stable",
    "Bắt đầu": "Start",
    "Chuyên gia": "Expert",
    "Chọn chế độ": "Select mode",
    "Cơ bản": "Basic",
    "Dừng": "Stop",
    "Dừng Test": "Stop Test",
    "Ghi âm": "Record",
    "Giao diện": "Interface",
    "Ngôn ngữ": "Language",
    "Phát": "Play",
    "Sẵn sàng": "Ready",
    "Thoát": "Exit",
    "Tiếp": "Next",
    "Tiếp tục": "Continue",
    "Trang chủ": "Home",
    "Trước": "Previous",
    "Trắng": "White",
    "Tối": "Dark",
    "Xanh Dương": "Blue",
    "Xanh Lá": "Green",
    "Xóa vết vẽ": "Clear drawing",
    "Công suất": "Power",
    "Giám sát hệ thống": "System monitoring",
    "Giám sát nhiệt độ và cảm biến": "Temperature and sensor monitoring",
    "Hiệu năng": "Performance",
    "Kết nối mạng": "Network connection",
    "Kiểm tra mạng": "Network test",
    "Nhiệt độ & Hiệu năng": "Temperature & Performance",
    "Phần cứng": "Hardware",
    "Sức khỏe pin": "Battery health",
    "Sức khỏe ổ cứng (S.M.A.R.T)": "Hard drive health (S.M.A.R.T)",
    "Test riêng lẻ": "Individual test",
    "Tổng Test": "Total Test",
    "Tổng kết": "Summary",
    "Tổng quan": "Overview",
    "Tỷ Lệ Đạt": "Pass Rate",
    "Copy thành công": "Copy successful",
    "Đã copy báo cáo vào clipboard!": "Report copied to clipboard!",
    "Đã hiển thị checklist": "Checklist displayed",
    "Đang chạy": "Running",
    "Đang kiểm tra": "Checking",
    "Đang test": "Testing",
    "Đang tải": "Loading",
    "Lỗi Worker": "Worker Error",
    "Phân tích pin hoàn thành": "Battery analysis completed",
    "Test hoàn thành": "Test completed",
    "LAPTOP CÓ VẤN ĐỀ NGHIÊM TRỌNG": "LAPTOP HAS SERIOUS ISSUES",
    "LAPTOP CẦN CHÚ Ý": "LAPTOP NEEDS ATTENTION",
    "LAPTOP TÌNH TRẠNG TỐT": "LAPTOP IN GOOD CONDITION",
    "Laptop hoạt động ổn định, có thể mua với giá hợp lý.": "Laptop works stably, can buy at reasonable price.",
    "Nhiều lỗi phát hiện, không khuyến nghị mua hoặc cần giảm giá mạnh.": "Many errors detected, not recommended to buy or need strong discount.",
    "Âm thanh rõ ràng": "Clear audio",
    "Hệ thống âm thanh có vấn đề": "Audio system has issues",
    "Hệ thống âm thanh tốt": "Audio system good",
    "Màn hình bình thường": "Screen normal",
    "Pin tốt": "Battery good",
    "Thiết bị nhập tốt": "Input devices good",
    "Tốc độ tốt": "Good speed",
    "Webcam có lỗi": "Webcam error",
    "Webcam hoạt động tốt": "Webcam working well",
    "Webcam test sẵn sàng": "Webcam test ready",
    "XUẤT BÁO CÁO": "EXPORT REPORT",
    "Xuất Excel": "Export Excel",
    "Xuất PDF": "Export PDF",
    "CÔNG CỤ CHUYÊN NGHIỆP BỔ SUNG": "ADDITIONAL PROFESSIONAL TOOLS",
    "HƯỚNG DẪN SỬ DỤNG CÔNG CỤ": "TOOL USAGE GUIDE",
    "Để kiểm tra sâu hơn, hãy sử dụng các công cụ chuyên nghiệp sau:": "For deeper check, use these professional tools:",
    "Lệnh cài đặt:": "Install command:",
    "Tải từ trang chủ": "Download from homepage",
    "Cách thực hiện:": "How to perform:",
    "Tại sao cần test?": "Why test?",
    "Tần số": "Frequency",
    "Tốc độ": "Speed",
    "kích hoạt vĩnh viễn": "permanently activated",
    "sẽ hết hạn": "will expire",
    "Không thể bắt sự kiện bàn phím do thiếu quyền Admin/root. Vui lòng chạy lại ứng dụng với quyền quản trị viên.": "Cannot capture keyboard events due to lack of Admin/root privileges. Please run application with administrator rights.",

}

def t(text):
    """Translation wrapper"""
    if not text or not isinstance(text, str):
        return text
    
    # Always read from main module's CURRENT_LANG
    try:
        import sys
        if 'main_enhanced_auto' in sys.modules:
            lang = sys.modules['main_enhanced_auto'].CURRENT_LANG
        else:
            lang = _CURRENT_LANG
    except:
        lang = _CURRENT_LANG
    
    return VI_TO_EN.get(text, text) if lang == "en" else text

def set_language(lang):
    """Set current language"""
    global _CURRENT_LANG
    _CURRENT_LANG = lang

def get_language():
    """Get current language"""
    return _CURRENT_LANG
