#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Translate ALL remaining Vietnamese strings to English"""

# Comprehensive translations
ALL_TRANS = {
    " vào ": " to ",
    "- Ổ": "- Drive",
    "1-2 phút": "1-2 minutes",
    "2-3 phút": "2-3 minutes",
    "Bị dừng bởi người dùng": "Stopped by user",
    "CPU có vấn đề": "CPU has issues",
    "CPU hoạt động tốt": "CPU working well",
    "Camera chưa khởi động - Khung hình 640x480": "Camera not started - Frame 640x480",
    "Camera đã dừng": "Camera stopped",
    "Chưa có kết quả test nào": "No test results yet",
    "Chức năng đang phát triển": "Feature in development",
    "Click phải:": "Right click:",
    "Click phải: 0": "Right click: 0",
    "Click trái:": "Left click:",
    "Click trái: 0": "Left click: 0",
    "Các thông tin trên được đọc trực tiếp từ BIOS/UEFI và không thể giả mạo từ Windows.\\nHãy so sánh với thông tin quảng cáo của người bán!": "Info above read directly from BIOS/UEFI, cannot be faked from Windows.\\nCompare with seller's advertised specs!",
    "Cần cài: pip install pandas openpyxl": "Need: pip install pandas openpyxl",
    "Cần cài: pip install reportlab": "Need: pip install reportlab",
    "Dựa trên phân tích trên, đánh giá tình trạng pin:": "Based on analysis above, battery condition:",
    "ESC để dừng": "ESC to stop",
    "GPU Stress Test - Nhấn ESC để thoát": "GPU Stress Test - Press ESC to exit",
    "GPU có vấn đề": "GPU has issues",
    "GPU hoạt động tốt": "GPU working well",
    "GPU không ổn định": "GPU unstable",
    "GPU ổn định": "GPU stable",
    "Gợi ý kiểm tra:": "Check suggestions:",
    "Hoàn thành kiểm tra!\\n\\nBạn có muốn thoát ứng dụng không?": "Testing completed!\\n\\nDo you want to exit?",
    "Hệ thống âm thanh quan trọng cho giải trí và họp trực tuyến. Loa bị rè, micro không hoạt động sẽ ảnh hưởng đến trải nghiệm multimedia.": "Audio system important for entertainment and online meetings. Distorted speakers or broken mic affects multimedia experience.",
    "Không thể đọc S.M.A.R.T": "Cannot read S.M.A.R.T",
    "Không tìm thấy": "Not found",
    "Không tìm thấy CPU": "CPU not found",
    "Không tìm thấy GPU": "GPU not found",
    "Không tìm thấy ổ cứng": "Hard drive not found",
    "Không xác định": "Unknown",
    "Kiểm Tra BIOS": "BIOS Check",
    "Kém": "Poor",
    "Kết nối mạng ổn định quan trọng cho công việc và giải trí. Test này kiểm tra tốc độ, độ trễ và chất lượng kết nối WiFi/Ethernet.": "Stable network connection important for work and entertainment. This test checks speed, latency and WiFi/Ethernet quality.",
    "Kết quả CPU Test:": "CPU Test Result:",
    "Kết quả GPU Test:": "GPU Test Result:",
    "Kết quả: Không thể so sánh (thiếu dữ liệu)": "Result: Cannot compare (missing data)",
    "Lưu báo cáo Excel": "Save Excel report",
    "Lưu báo cáo PDF": "Save PDF report",
    "Lỗi/Cảnh báo": "Error/Warning",
    "Model Ổ Cứng": "Hard Drive Model",
    "Một máy tính có bản quyền Windows hợp lệ đảm bảo bạn nhận được các bản cập nhật bảo mật quan trọng và tránh các rủi ro pháp lý.": "Valid Windows license ensures security updates and avoids legal risks.",
    "Ngày BIOS": "BIOS Date",
    "Nhấn 'Bắt đầu Test' trong 2-5 phút. Theo dõi biểu đồ nhiệt độ. Nếu nhiệt độ ổn định dưới 95°C và không có hiện tượng treo máy, hệ thống tản nhiệt hoạt động tốt.": "Click 'Start Test' for 2-5 minutes. Monitor temperature chart. If temp stays below 95°C without freezing, cooling works well.",
    "Nhấn 'Bắt đầu Test' để chạy lệnh kiểm tra trạng thái kích hoạt Windows. Kết quả sẽ hiển thị bên dưới.": "Click 'Start Test' to check Windows activation status. Results will display below.",
    "Nhấn 'Bắt đầu Test' để chạy test kết hợp 3-5 phút. Quan sát nhiệt độ và hiệu năng.": "Click 'Start Test' to run combined test for 3-5 minutes. Observe temperature and performance.",
    "Nhấn 'Bắt đầu Test' để chạy test màn hình tự động. Test sẽ hiển thị các màu khác nhau, nhấn ESC để dừng bất cứ lúc nào.": "Click 'Start Test' to run automatic screen test. Test displays different colors, press ESC to stop anytime.",
    "Nhấn 'Bắt đầu Test' để kiểm tra kết nối Internet, DNS, tốc độ mạng và thông tin WiFi.": "Click 'Start Test' to check Internet connection, DNS, network speed and WiFi info.",
    "Nhấn 'Bắt đầu Test' để kiểm tra tốc độ ổ cứng thực tế.": "Click 'Start Test' to check actual hard drive speed.",
    "Nhấn 'Bắt đầu Test' để mở camera. Kiểm tra chất lượng hình ảnh, độ phân giải và che camera để test phát hiện vật cản.": "Click 'Start Test' to open camera. Check image quality, resolution and cover camera to test obstruction detection.",
    "Nhấn 'Bắt đầu Test' để đọc thông tin phần cứng từ BIOS. Sau đó so sánh với thông tin quảng cáo của người bán.": "Click 'Start Test' to read hardware info from BIOS. Then compare with seller's advertised specs.",
    "Nhấn 'Start Monitor' để bắt đầu giám sát. Có thể chạy Stress Test để kiểm tra khả năng tản nhiệt dưới tải cao.": "Click 'Start Monitor' to begin monitoring. Can run Stress Test to check cooling under high load.",
    "Phát bài nhạc test và kiểm tra micro với biểu đồ sóng âm.": "Play test music and check microphone with waveform chart.",
    "Pin là nguồn năng lượng di động của laptop. Pin hỏng hoặc chai sẽ giảm thời gian sử dụng và có thể gây nguy hiểm.": "Battery is laptop's mobile power source. Damaged or degraded battery reduces usage time and may be dangerous.",
    "Pygame không có sẵn. Cài đặt: pip install pygame": "Pygame not available. Install: pip install pygame",
    "Rất tốt": "Excellent",
    "So sánh tự động:": "Auto compare:",
    "Sẵn sàng test": "Ready to test",
    "Test sẽ hiển thị: Đen → Trắng → Đỏ → Xanh Lá → Xanh Dương\\nMỗi màu 3 giây. Nhấn ESC để dừng.": "Test displays: Black → White → Red → Green → Blue\\nEach color 3 seconds. Press ESC to stop.",
    "Test tổng hợp CPU+GPU+RAM để đảm bảo hệ thống ổn định dưới tải nặng kéo dài.": "Combined CPU+GPU+RAM test to ensure system stability under prolonged heavy load.",
    "Test đã được dừng bởi người dùng.": "Test stopped by user.",
    "Thành công": "Success",
    "Thông tin pin sẽ được tự động thu thập. Kiểm tra các thông số dưới đây và đánh giá tình trạng pin.": "Battery info will be automatically collected. Check parameters below and assess battery condition.",
    "Thời gian:": "Time:",
    "Tiến độ:": "Progress:",
    "Trung bình": "Average",
    "Trạng thái:": "Status:",
    "Tình trạng vật lý tổng thể của máy như thế nào?": "What is overall physical condition?",
    "Tốc độ chậm": "Slow speed",
    "Tốc độ đọc/ghi ảnh hưởng trực tiếp đến hiệu năng hệ thống.": "Read/write speed directly affects system performance.",
    "Webcam cần thiết cho video call và họp trực tuyến. Camera không hoạt động hoặc chất lượng kém sẽ ảnh hưởng đến giao tiếp.": "Webcam necessary for video calls and online meetings. Non-working camera or poor quality affects communication.",
    "Windows chưa được kích hoạt": "Windows not activated",
    "Windows được kích hoạt vĩnh viễn": "Windows permanently activated",
    "Yếu": "Weak",
    "\\n❌ NHỮNG ĐIỀU CẦN TRÁNH:": "\\n❌ THINGS TO AVOID:",
    "\\n💡 Cách khắc phục:": "\\n💡 How to fix:",
    "\\n📋 CÁCH SẠC VÀ SỬ DỤNG PIN ĐÚNG CÁCH:": "\\n📋 PROPER BATTERY CHARGING AND USAGE:",
    "Đang chạy vòng lặp stress...": "Running stress loop...",
    "Đang khởi tạo Pygame...": "Initializing Pygame...",
    "Đang xả cache ghi xuống đĩa...": "Flushing write cache to disk...",
    "Đóng ứng dụng\\nLaptopTester Pro": "Close\\nLaptopTester Pro",
    "Để xác minh kết quả AI và kiểm tra sâu hơn, hãy sử dụng các công cụ chuyên nghiệp sau:": "To verify AI results and check deeper, use these professional tools:",
    "Đối chiếu thông tin dưới đây với bước trước và với thông tin quảng cáo. Nếu mọi thứ khớp, chọn 'Cấu hình khớp'.": "Cross-check info below with previous step and advertised specs. If everything matches, select 'Configuration matches'.",
    "Ổ cứng:": "Hard drive:",
    "• Cập nhật BIOS và driver": "• Update BIOS and drivers",
    "• Di chuyển chuột/touchpad trên vùng test\\n• Click trái và phải để test\\n• Thử cuộn 2 ngón tay (touchpad)": "• Move mouse/touchpad on test area\\n• Left and right click to test\\n• Try two-finger scroll (touchpad)",
    "• Kiểm tra BIOS: CPU Frequency → Auto/Dynamic": "• Check BIOS: CPU Frequency → Auto/Dynamic",
    "• Kiểm tra adapter nguồn (phải đúng watt)": "• Check power adapter (must be correct wattage)",
    "• Power limit - Nguồn không đủ mạnh": "• Power limit - Insufficient power",
    "• Quá nhiệt (>85°C) - Tản nhiệt kém": "• Overheating (>85°C) - Poor cooling",
    "• Tắt phần mềm quản lý nguồn của hãng": "• Disable manufacturer's power management software",
    "• Vệ sinh quạt tản nhiệt, thay keo tản nhiệt": "• Clean cooling fan, replace thermal paste",
    "• Windows: Chế độ nguồn → Hiệu năng cao": "• Windows: Power mode → High performance",
    "← Quay lại": "← Back",
    "⏹️ Dừng": "⏹️ Stop",
    "⏹️ Đã dừng nhạc": "⏹️ Music stopped",
    "▶️ Chạy Test": "▶️ Run Test",
    "⚙️ Checklist Kiểm Tra BIOS Chi Tiết": "⚙️ Detailed BIOS Check Checklist",
    "⚠️ Cảnh báo: Có sai lệch - Kiểm tra lại!": "⚠️ Warning: Mismatch detected - Check again!",
    "⚠️ LƯU Ý: Ứng dụng được phát triển dựa trên AI nên có thể có sai sót. Khuyến khích kiểm tra thêm bằng các ứng dụng chuyên dụng được cung cấp bên dưới.": "⚠️ NOTE: App developed with AI may have errors. Recommend additional checks with specialized apps provided below.",
    "⚠️ TÌNH TRẠNG: Pin bắt đầu suy giảm": "⚠️ CONDITION: Battery starting to degrade",
    "⚠️ TÌNH TRẠNG: Pin suy giảm nghiêm trọng": "⚠️ CONDITION: Battery severely degraded",
    "⚡ Hiệu Năng CPU:": "⚡ CPU Performance:",
    "⛔ CẢNH BÁO NGHIÊM TRỌNG - MẬT KHẨU BIOS": "⛔ CRITICAL WARNING - BIOS PASSWORD",
    "✅ Hoàn thành phát file stereo test": "✅ Stereo test file playback completed",
    "✅ Hoàn thành test âm thanh": "✅ Audio test completed",
    "✅ Kết quả: Khớp": "✅ Result: Match",
    "✅ Phát tone test 440Hz": "✅ Playing 440Hz test tone",
    "✅ Test hoàn thành": "✅ Test completed",
    "✅ TÌNH TRẠNG: Pin còn tốt": "✅ CONDITION: Battery still good",
    "✅ Đã dừng ghi âm": "✅ Recording stopped",
    "✅ Đã ghi âm 5 giây": "✅ Recorded 5 seconds",
    "✓ CPU Tốt": "✓ CPU Good",
    "✓ Chấp Nhận": "✓ Accept",
    "✓ Hệ thống ổn định": "✓ System stable",
    "✖ Đóng": "✖ Close",
    "✗ CPU Có Vấn Đề": "✗ CPU Has Issues",
    "✗ Có vấn đề": "✗ Has issues",
    "❌ Không phát hiện pin hoặc đây là máy bàn": "❌ No battery detected or this is desktop",
    "❌ Không tìm thấy camera hoạt động": "❌ No working camera found",
    "❌ OpenCV không có sẵn. Cài đặt: pip install opencv-python": "❌ OpenCV not available. Install: pip install opencv-python",
    "🇻🇳 Tiếng Việt": "🇻🇳 Vietnamese",
    "🎤 Ghi âm": "🎤 Record",
    "🎤 Đang ghi âm... Nói vào micro": "🎤 Recording... Speak into microphone",
    "🎵 Phát Stereo Test": "🎵 Play Stereo Test",
    "🎵 Phát file stereo_test.mp3...": "🎵 Playing stereo_test.mp3...",
    "🏠 Trang chủ": "🏠 Home",
    "💡 Khuyến khích so sánh kết quả với các tools này để đảm bảo độ chính xác cao nhất.": "💡 Recommend comparing results with these tools to ensure highest accuracy.",
    "💡 Khả Năng Sử Dụng Phần Cứng": "💡 Hardware Capability",
    "💡 LỜI KHUYÊN VỀ SỨC KHỎE PIN": "💡 BATTERY HEALTH ADVICE",
    "💻 Vỏ Máy & Bản Lề:": "💻 Chassis & Hinges:",
    "📊 Kết Quả CPU Stress Test": "📊 CPU Stress Test Results",
    "📊 Kết Quả GPU Stress Test": "📊 GPU Stress Test Results",
    "📊 Phân Tích Chi Tiết": "📊 Detailed Analysis",
    "📋 Checklist Kiểm Tra Bản Quyền": "📋 License Check Checklist",
    "📋 Checklist Định Danh Phần Cứng": "📋 Hardware Fingerprint Checklist",
    "📋 Chi Tiết Kết Quả Từng Bước": "📋 Step-by-Step Results Details",
    "📍 237/1C Tôn Thất Thuyết, P. Vĩnh Hội, (P.3, Q.4 cũ), TPHCM": "📍 237/1C Ton That Thuyet, Vinh Hoi Ward, (Old Ward 3, Dist 4), HCMC",
    "🔋 Mức Pin Hiện Tại:": "🔋 Current Battery Level:",
    "🔋 Phân Tích Pin Chi Tiết": "🔋 Detailed Battery Analysis",
    "🔌 Cổng Kết Nối:": "🔌 Ports:",
    "🔍 Checklist Kiểm Tra Ngoại Hình Chi Tiết": "🔍 Detailed Physical Inspection Checklist",
    "🔍 Nguyên nhân có thể:": "🔍 Possible causes:",
    "🔑 Cách Vào BIOS:": "🔑 How to Enter BIOS:",
    "🔒 BẢO MẬT KHÁC:": "🔒 OTHER SECURITY:",
    "🔒 PHÁT HIỆN KHÓA XUNG CPU": "🔒 CPU FREQUENCY LOCK DETECTED",
    "🔧 Chọn Bài Test Riêng Lẻ": "🔧 Select Individual Tests",
    "🔩 Ốc Vít & Tem Bảo Hành:": "🔩 Screws & Warranty Seals:",
    "🔴 LENOVO THINKPAD - KIỂM TRA ĐẶC BIỆT:": "🔴 LENOVO THINKPAD - SPECIAL CHECK:",
    "🔴 THINKPAD - CÀI ĐẶT KHÁC:": "🔴 THINKPAD - OTHER SETTINGS:",
    "🚨 CẢNH BÁO: Nhiệt độ nguy hiểm! CPU có thể bị hỏng.": "🚨 WARNING: Dangerous temperature! CPU may be damaged.",
    "🤖 Đánh giá của AI": "🤖 AI Assessment"
}

# Read lang_wrapper
with open('lang_wrapper.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Replace all
count = 0
for vi, en in ALL_TRANS.items():
    vi_esc = vi.replace('\\', '\\\\').replace('"', '\\"')
    en_esc = en.replace('\\', '\\\\').replace('"', '\\"')
    old = f'    "{vi_esc}": "{vi_esc}",'
    new = f'    "{vi_esc}": "{en_esc}",'
    if old in content:
        content = content.replace(old, new)
        count += 1

# Write
with open('lang_wrapper.py', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Translated {count} strings")
